### ISSUE TITLE
ipv6 para de funcionar

### ISSUE THREAD

**Issue by alacn1** [tripleoxygen/v5471#2]
Depois de algumas horas o prefixo IPv6 deixa de ser anunciado pelo roteador.
Firmware: B14103-GVT-OXY-42006

Isso acontece porque o radvd está configurado com:
DecrementLifetimes on;
Essa config faz o radvd ir diminuindo o valid lifetime até receber um SIGUSR1 para resetar o tempo.

Como ele nunca recebe o SIGUSR1, o tempo zera e ele para de anunciar o prefixo.

Isso poderia ser corrigido comentando com um # na linha "DecrementLifetimes on;" no arquivo:
/etc/bewan/lib/radvd

**Comment by tripleoxygen** [comment]
Atualizei o README com as novas instruções para construir a imagem. Infelizmente tive que tirar o rootfs do versionamento (não dá muito certo com o GitHub).
Construa lá com os fixes e nos atualize. :)

**Comment by TopFuel** [comment]
@tripleoxygen Muito obrigado por disponibilizar as instruções.
Tive o mesmo problema com o IPV6, vou testar o fix do @alacn1 e aviso se o problema for corrigido.

**Comment by tripleoxygen** [comment]
Veja a atualização nas instruções sobre o unpack_rootfs.

**Comment by TopFuel** [comment]
@tripleoxygen Não estava conseguindo construir a imagem corretamente no Ubuntu 16.10, mas acho que descobri o problema, no arquivo [build.sh na linha 32](https://github.com/tripleoxygen/v5471/blob/b8be7966d0877f5db931a8f91916cc5eea339eb1/build.sh#L32) em vez do printf colocar o hex no offset `0x14` ele estava colocando o caractere '\\'.

Depois de procurar por um tempo, a solução que encontrei foi mudar o shebang de `#!/bin/sh` para `#!/usr/bin/env bash`.
Não tenho muita experiencia com linux então não sei se é o jeito correto de corrigir esse problema, mas parece que funcionou, ainda não testei no modem, vou testar mais tarde.

Agora sobre o header você muda ele manualmente para ter as informações `B14103-GVT-OXY-42007.bin`, `GVT-OXY` e a data de criação correta?
Tem algum problema em deixar as informações originais ou devo alterar elas?

**Edit:**
Testei no modem e parece que está tudo certo, a unica coisa que está diferente da versão 42007 oficial é que na pagina `Sobre o Power Box` mostra a `Versão de Software` do firmware stock por que deixei as informações do header originais.

**Comment by tripleoxygen** [comment]
Não precisa mudar se não quiser, é meramente estética. Normalmente a informação da versão não vem desse cabeçalho, mas alterei a página de Sobre para usá-la, assim internamente, o modem se comporta (e reporta via TR069) como a versão stock base. Assim evitamos problemas como ISPs detectando modem com fw custom, etc.

**Comment by TopFuel** [comment]
@tripleoxygen Entendi, obrigado.
Uma outra duvida, qual OS você usou para construir as imagens?

@alacn1 Você acha que teria um jeito da fazer o radvd receber o sinal SIGUSR1?
Eu sei que tem como mandar o sinal com o comando `kill -USR1 [pid-do-radvd]` (ainda não testei se funciona, vou testar mais tarde), mas a duvida seria quando mandar o sinal.

Eu estou testando o ipv6 e investigando uns outros problemas que encontrei, um deles é que o processador fica um uso alto (+50%) e faz com que a internet fique instável, parece vir do `dhcp6c`.

**Comment by alacn1** [comment]
@TopFuel O signal deveria ser enviado para o radvd quando renovar o Prefix Delegation (PD).
O "DecrementLifetimes" seria usado só quando há uma tratativa de renovação de PD.
Mas esse PD é válido pelo tempo de conexão, por isso o modem não trata a renovação.
Assim o correto é remover a linha do "DecrementLifetimes on;".

Uma gambiarra seria botar no cron para ficar enviando o signal.
Para isso conecte no modem por telnet ou ssh e faça:
```
cli
cd Services_Cron_StaticTable
mk 1
set Description 'radvd signal'
set Command "/bin/ash -c 'if [ -f /var/run/radvd-lan1.pid ] ; then kill -SIGUSR1 `cat /var/run/radvd-lan1.pid` ; fi'"
set TimeSpec '*/5\\t*\\t*\\t*\\t*\\t'
set Enable 1
fcommit
```

Note que há um bug no TimeSpec e não dá para usar espaço entre os asteriscos.

**Comment by TopFuel** [comment]
@alacn1 Então nesse caso o correto é remover o `DecrementLifetimes` em vez de enviar o sinal?
Eu estava achando que o correto seria enviar o sinal e que remover o `DecrementLifetimes` seria uma gambiarra.
Quando seria correto usar o `DecrementLifetimes`?

Mais tarde vou remover ele e construir uma imagem para testar.

**Comment by alacn1** [comment]
@TopFuel `DecrementLifetimes` seria utilizado quando precisa renovar o Prefix Delegation sem reconectar.
Seria o equivalente a trocar de IPv4 sem cair a conexão.

**Comment by navossoc** [comment]
Minha gambiarra temporária é desabilitar ou habilitar o WPS do wifi...

Provavelmente algum script ali da trigger em algum evento de rede e resolve o problema, mas o ideal era fixar mesmo.
(Pra isso estou atrás do unbrick)

[]'s

**Comment by alacn1** [comment]
montei uma firmware com o radvd corrigido e IPv6 ativo,
https://github.com/alacn1/pace_v5471/tree/master/release

**Comment by navossoc** [comment]
Ainda não resolve o meu unbrick.

[]'s

**Comment by alacn1** [comment]
para unbrick recupere pelo multicast mode:
https://github.com/alacn1/pace_v5471/blob/master/README.md
