### ISSUE TITLE
boot loop

### ISSUE THREAD

**Issue by alacn1** [tripleoxygen/v5471#3]
como recupero de um boot loop?

**Comment by alacn1** [comment]
Estava fazendo alguns testes, porem gerei um squashfs com permissões rwx erradas. Agora o modem fica reiniciando. Não consigo contato pela rede. Ele fica em loop e acende todas as luzes a cada 15 segundos aproximadamente.

**Comment by tripleoxygen** [comment]
Uma forma de recuperá-lo é pelo multicast boot: ligando o modem com o reset pressionado. Documentei o protocolo há algum tempo, vou ver se acho e implemento uma ferramenta.

**Comment by alacn1** [comment]
estou parado no multicast boot tentando descobrir como mandar a firmware

**Comment by alacn1** [comment]
já consegui, tive q montar uma ferramenta para fazer upload da firmware no modo multicast

**Comment by TopFuel** [comment]
@alacn1 Que bom que conseguiu, vi que atualizou a ferramenta no seu repositório, obrigado.

**Comment by tripleoxygen** [comment]
@alacn1 excelente! Sua implementação bate com minhas anotações. Documentou a partir da engenharia reversa do bootloader?

**Comment by alacn1** [comment]
isso, passei várias e várias horas comentando linhas de asm e interpretando o que cada parte fazia...

**Comment by navossoc** [comment]
Estava afim de começar a fuçar nesse firmware, mas sem como dar unbrick é meio inviável.

Deixei algo passar aqui? Onde está essa ferramenta?
Por acaso é o mesmo procedimento do 2764? BOOTP com um TFTP?

[]'s

**Comment by alacn1** [comment]
desde que não tenha apagado o bootloader, use o "multicast mode" para testar firmware ou fazer unbrick:
https://github.com/alacn1/pace_v5471/blob/master/README.md
