### ISSUE TITLE
updatefw

### ISSUE THREAD

**Issue by alacn1** [tripleoxygen/v5471#4]
caso tenha interesse e queira validar, montei uma ferramenta para facilitar modificar as firmwares:
https://github.com/alacn1/pace_v5471

ela permite exportar/importar o rootfs, sem ter que ficar modificando manualmente por hexadecimal.

**Comment by TopFuel** [comment]
Testei e funcionou muito bem, alterei o `build.sh` para usar sua ferramenta, quem quiser está aqui: 
https://gist.github.com/TopFuel/ec19b14db13e57ea775366b5e4038530

- Removi a parte do `rootfs.patched` e a alteração do magic e flag pois sua ferramenta já faz isso.
- No final movo os arquivos `header`, `kernel`, `rootfs` e o bin original para uma pasta chamada `build-files` para deixar a pasta do build mais limpa.
- Alterei o shebang de `#!/bin/sh` para `#!/usr/bin/env bash` pois estava tendo uns problemas com o shebang original no Ubuntu 16.10.

O `updatefw` deve estar no mesmo diretório do `build.sh`.

Não testei no modem mas a imagem parece ser construída corretamente.

Obrigado por disponibilizar a ferramenta.

**Edit:** Atualizei o gist com algumas alterações:

- Adicionei um parâmetro para passar o `release name` na hora de chamar o `build.sh`, exemplo: 
 `./build.sh 12345 GVT-ABC`
 Se não passar o segundo parâmetro o `release name` fica com o valor padrão que é: `GVT-OXY`.
